{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "fluentd-relay.ingressName" . }}
  labels: {{- include "fluentd-relay.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host | default "fluentd-relay" }}
      http:
        paths:
          - backend:
              serviceName: {{ include "fluentd-relay.serviceName" . }}
              servicePort: {{ include "fluentd-relay.servicePort" . }}
{{- end -}}
