{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd-relay.serviceName" . }}
  labels: {{- include "fluentd-relay.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ include "fluentd-relay.servicePort" . }}
      targetPort: {{ include "fluentd-relay.servicePort" . }}
      protocol: TCP
  selector: {{ include "fluentd-relay.matchLabels" . | nindent 4 }}
{{- end -}}
