apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels: {{ include "proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "proxy.labels" . | nindent 8 }}
    spec:
      securityContext: {{ toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "proxy.fullname" . }}
          securityContext: {{ toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: healthcheck
              containerPort: 80
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: healthcheck
          readinessProbe:
            httpGet:
              path: /
              port: healthcheck
          resources: {{ toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "proxy.configName" . }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
