{{- if .Values.ingress.enabled -}}
{{- if .Values.endpoints.no_auth -}}
{{- $baseHostname := .Values.baseHostname -}}
{{- $fullname := (include "proxy.fullname" .) -}}
{{- $servicePort := (include "proxy.servicePort" .) -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "proxy.fullname" . }}
  labels: {{ include "proxy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    {{- range .Values.endpoints.no_auth }}
    - {{ printf "%s.%s" .host $baseHostname | quote }}
    {{- end }}
    secretName: {{ .Values.secretName }}
  rules:
  {{- range .Values.endpoints.no_auth }}
  - host: {{ printf "%s.%s" .host $baseHostname | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullname }}
          servicePort: {{ $servicePort }}
  {{- end }}
{{- end -}}
{{- end -}}
