apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "proxy.servicePort" . }}
      targetPort: {{ include "proxy.servicePort" . }}
      protocol: TCP
      name: http
  selector: {{ include "proxy.selectorLabels" . | nindent 4 }}
