apiVersion: v1
name: elastichq
version: 0.1.0
appVersion: 3.5.12
description: An elasticsearch management tool
keywords:
  - elasticsearch
  - logging
  - logs
  - data
home: https://www.elastichq.org/
maintainers:
  - name: Zan
    email: zan.loy@gmail.com
icon: https://bitnami.com/assets/stacks/elasticsearch/img/elasticsearch-stack-110x117.png
