image:
  registry: docker.io
  repository: elastichq/elasticsearch-hq
  tag: release-v3.5.12
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

## String to partially override elastic-go.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override elastic-go.fullname template
##
# fullnameOverride:

elasticsearch:
  host: prod8-elasticsearch-client.logging
  port: 9200

ingress:
  enabled: true
  host: elastichq.prod8.bip.va.gov
  secret: elastichq-tls
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth.prod8.bip.va.gov/oauth2/start?rd=https://$host$request_uri$is_args$args"
    nginx.ingress.kubernetes.io/auth-url: "https://oauth.prod8.bip.va.gov/oauth2/auth"
