# Default values for s3-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

oauth:
  signin: ""
  url: ""

baseHostname: proxy.stage8.bip.va.gov
endpoints:
  no_auth:
    - host: vefs-rrc-ivv
      endpoint: project-vefs-rrc-ivv-bucket.s3.us-gov-west-1.amazonaws.com
    - host: vefs-rrc-uat
      endpoint: project-vefs-rrc-uat-bucket.s3.us-gov-west-1.amazonaws.com
    - host: vefs-rrc-pdt
      endpoint: project-vefs-rrc-pdt-bucket.s3.us-gov-west-1.amazonaws.com
    - host: vefs-rrc-pat
      endpoint: project-vefs-rrc-pat-bucket.s3.us-gov-west-1.amazonaws.com
    - host: vefs-rrc-demo
      endpoint: project-vefs-rrc-demo-bucket.s3.us-gov-west-1.amazonaws.com

secretName: proxy-stage-secret

deployment:
  replicaCount: 2
  image:
    repository: nginx
    tag: '1.18'
    pullPolicy: IfNotPresent
  resources: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
