# Default values for wlpxy.

deployment:
  haproxy:
    image: container-registry.prod8.bip.va.gov/bip/haproxy
    tag: "2.3.5-alpine"
  nginx:
    image: container-registry.prod8.bip.va.gov/bip/wlpxy/nginx
    tag: "1.1"
#  annotations:
#    iam.amazonaws.com/role: project-wlpxy

# The endpoints for the proxy
# port defaults to 7001
endpoints:
  - name: cola-awards
    ip: 10.247.68.60
  - name: cola-core
    ip: 10.247.69.158
  - name: cola-rating
    ip: 10.247.68.221
  - name: cola-haz
    ip: 10.247.68.245
    port: 8001
  - name: cola-res
    ip: 10.247.68.221
    port: 9101
  - name: cola-spring
    ip: 10.247.69.157
    port: 8100
  #
  - name: perf-awards
    ip: 10.247.67.224
  - name: perf-core
    ip: 10.247.67.121
  - name: perf-rating
    ip: 10.247.67.125
  - name: perf-haz
    ip: 10.247.66.137
    port: 8001
  - name: perf-res
    ip: 10.247.67.125
    port: 9101
  - name: perf-spring
    ip: 10.247.66.166
    port: 8100
  #
  - name: prdtst-awards
    ip: 10.247.69.239
  - name: prdtst-core
    ip: 10.247.69.53
  - name: prdtst-rating
    ip: 10.247.69.108
  - name: prdtst-haz
    ip: 10.247.68.57
    port: 8001
  - name: prdtst-res
    ip: 10.247.69.108
    port: 9101
  - name: prdtst-spring
    ip: 10.247.68.146
    port: 8100
  #
  - name: pre-awards
    ip: 10.247.66.183
  - name: pre-core
    ip: 10.247.66.206
  - name: pre-rating
    ip: 10.247.67.112
  - name: pre-haz
    ip: 10.247.67.2
    port: 8001
  - name: pre-res
    ip: 10.247.67.112
    port: 9101
  - name: pre-spring
    ip: 10.247.66.126
    port: 8100
  #
  - name: prod-awards
    ip: 10.247.65.215
  - name: prod-core
    ip: 10.247.65.25
  - name: prod-rating
    ip: 10.247.64.29
  - name: prod-haz
    ip: 10.247.64.248
    port: 8001
  - name: prod-res
    ip: 10.247.64.29
    port: 9101

  #
  - name: oem
    ip: 10.247.67.214
    port: 7802


endpoints_https:
  - name: prod-spring
    ip: 10.247.65.39
    port: 8100


ingress:
  enabled: true
  domain: wlpxy.prod8.bip.va.gov
  tls:
    enabled: true
    secretname: wlpxy-tls

# vim: ts=2 sw=2 expandtab:
