---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-scaler-rb
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: scaler
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io
