---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scale-down
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.scale_down_time.minute }} {{ .Values.scale_down_time.hour }} * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          {{- range .Values.deployments }}
          - name: scale-down-{{ . }}
            image: bitnami/kubectl:latest
            command: ["kubectl", "scale", "deployment", {{ . | quote }}, "--replicas=0"]
          {{- end }}
          restartPolicy: OnFailure
          serviceAccount: scaler
