{{- if .Values.ingress.enabled -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dump-headers
spec:
  rules:
    - host: {{ required "A valid ingress host is required if ingress enabled. Try '--set ingress.host=test.example.com' or disable ingress with '--set ingress.enabled=false'." .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: dump-headers
              servicePort: {{ .Values.port }}
            path: /
{{- end -}}
