apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bip-ops-docs.fullname" . }}
  labels:
    {{- include "bip-ops-docs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels: {{ include "bip-ops-docs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "bip-ops-docs.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: download-site
          image: zanloy/alpine-va:1.2.0
          env:
            - name: GIT_SSH_COMMAND
              value: 'ssh -i /tmp/id_rsa -p 443 -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no"'
            - name: GIT_REPO
              value: {{ .Values.git.repo }}
            - name: SRC_PATH
              value: 'repo/site/*'
            - name: DEST_PATH
              value: '/usr/share/nginx/html/'
          volumeMounts:
            - name: sshkey
              mountPath: /ssh
            - name: document-root
              mountPath: /usr/share/nginx/html
          command: ['sh', '-c', 'cp /ssh/id_rsa /tmp/id_rsa && chmod 0400 /tmp/id_rsa && git clone $GIT_REPO repo && cp -Rv $SRC_PATH $DEST_PATH']
      containers:
        - name: {{ include "bip-ops-docs.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {{ toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
          - name: document-root
            mountPath: /usr/share/nginx/html
      volumes:
        - name: document-root
          emptyDir: {}
        - name: sshkey
          secret:
            secretName: {{ .Values.git.sshkey_secret }}
