{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "bip-ops-docs.fullname" . }}
  labels: {{ include "bip-ops-docs.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ include "bip-ops-docs.fullname" . }}
            servicePort: 80
