apiVersion: v1
kind: Service
metadata:
  name: {{ include "bip-ops-docs.fullname" . }}
  labels:
    {{- include "bip-ops-docs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector: {{ include "bip-ops-docs.selectorLabels" . | nindent 4 }}
