apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-proxy.fullname" . }}
  labels:
    {{- include "s3-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ include "s3-proxy.servicePort" . }}
      targetPort: {{ include "s3-proxy.servicePort" . }}
      protocol: TCP
      name: http
  selector: {{ include "s3-proxy.selectorLabels" . | nindent 4 }}
